### PR TITLE
Added a quote model. Random quote now taken from the database.

### PR DESCRIPTION
**Pull request by MarshalX**

### CODE REVIEW

**Comment by marxmit7** [comment]
@MarshalX  in this django project , I am using mysql as it's default db and you have used mongodb .Make me sure that this PR won't  break the whole project. Did you run this project on local machine ?

**Comment by MarshalX** [comment]
> @MarshalX in this django project , I am using mysql as it's default db and you have used mongodb .Make me sure that this PR won't break the whole project. Did you run this project on local machine ?

I use Django ORM. It will work with all databases. What exactly database depends on your configuration file(settings.py). I did not touch it(only turned off debug mode). You are configured work with mysql. It will work with it. Of course, I ran this project on my local machine.

**Comment by MarshalX** [comment]
You will need to apply migrations to your database. Migrations I put in a package "swachh/migrations"

**Comment by marxmit7** [comment]
Thanks @MarshalX  looks good to be merged:)

**Pull request merged**
